### ISSUE TITLE
demo of enhance category package dependency 

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#126]
related issue: #99 

There are another four packages in the enhanced category. I will need help to understand how to achieve that.

```
    gh,
    jsonlite,
    vctrs,
    pillar,
```

**Comment by dgkf** [comment]
After reading up more on "Enhances", I believe that what I was previously considering as "Enhances" should actually be "Suggests".

> The ‘Suggests’ field uses the same syntax as ‘Depends’ and lists packages that are not necessarily needed. This includes packages used only in examples, tests or vignettes (see Writing package vignettes), and packages loaded in the body of functions. E.g., suppose an example11 from package foo uses a dataset from package bar. Then it is not necessary to have bar use foo unless one wants to execute all the examples/tests/vignettes: it is useful to have bar, but not necessary. Version requirements can be specified but should be checked by the code which uses the package.
>
> Finally, the ‘Enhances’ field lists packages “enhanced” by the package at hand, e.g., by providing methods for classes from these packages, or ways to handle objects from these packages (so several packages have ‘Enhances: chron’ because they can handle datetime objects from chron even though they prefer R’s native datetime functions). Version requirements can be specified, but are currently not used. Such packages cannot be required to check the package: any tests which use them must be conditional on the presence of the package. (If your tests use e.g. a dataset from another package it should be in ‘Suggests’ and not ‘Enhances’.)  
>
> _from ["Writing R Extensions" 1.1.3 Package Dependencies](https://cran.r-project.org/doc/manuals/R-exts.html#Package-Dependencies)_

Furthermore, the documentation notes how to handle dependencies that are only considered _suggested_ in section [1.1.3.1 Suggested Packages](https://cran.r-project.org/doc/manuals/R-exts.html#Suggested-packages).

```r
   if (requireNamespace("rgl", quietly = TRUE)) {
      rgl::plot3d(...)
   } else {
      ## do something else not involving rgl.
   }
```

If we consider the `covr` package that we currently depend on. We might consider moving that to Suggets. We could consider doing something like this. 

```r
   if (requireNamespace("covr", quietly = TRUE)) {
     expr <- bquote(tools::testInstalledPackage(.(x$name), types = 'tests'))
     return(covr::package_coverage(path = x$path, type = "none", code = deparse(expr)))
   } else {
     # return some sort of null value, possibly causing risk metric to 
     # suggest installing the additional dependencies to enable this feature
   }
```

---

Note: I also realized when exploring this that we don't actually use `gh` anymore, so that one should be easy to remove.

**Comment by elong0527** [comment]
After evaluation, I have removed the `gh` from `import`. 

create new issues #144 and #145 for further alignment.
