### ISSUE TITLE
Add labels to score metrics

### ISSUE THREAD

**Issue by andyofsmeg** [pharmaR/riskmetric#129]
This would help automatical labelling in the riskassessment app.  The assess* functions have labels but these are not always applicable for scores.

For example, if the last 30 bug reports is scored, a suitable label might be "A percentage of last 30 BugReports whose status is 'closed'"

**Comment by elong0527** [comment]
require follow up discussion between @dgkf  and @marlycormar

**Comment by dgkf** [comment]
### Honing in on the problem

@marlycormar - Before discussing implementation, lets settle on how we want the information made available to the shiny app. 

For example, if we were to provide a tibble of scores, would a label describing the score be sufficient? If so, then I think we could add a description to each scoring function which could be extracted when the scoring function is applied. 

There is one tricky nuance here. That is that assessments are all scored individually, not as a column, and that the class within a column might vary. For example, using the last 30 bugs assesssment, ideally all assessments in the `pkg_assess` tibble output would have the class `c("pkg_metric_last_30_bugs_status" "pkg_metric")`. However, if one package failed, the assessment result will have the class `c("pkg_metric_error", "pkg_metric", ...)`. This is used so that errors can be scored as their own class, but also means that the scoring function that is used will vary across the assessment results.

So I think we need to do a bit of rethinking about this flow to appropriately accommodate this. 

### Possible Implementation

In the situation where an error occurs during an assessment, eg the last 30 bugs, perhaps we can return an error class as a subclass of the expected assessment class. 

```r
x <- pkg_ref("utils")  # utils has no BugReports defined, so will give an error
a <- pkg_assess(x)

class(a$bug_reports)
# [current]> [1] "pkg_metric_error" "pkg_metric" "simpleError" "error" "condition"
# [suggest]> [1] "pkg_metric_last_30_bugs_status" "pkg_metric" "error"
```

This might be preferred because the pkg_metric_* class would be the same regardless of whether an error is produced. Then we could find the appropriate scoring function (and pull a label attributed to it), but will need to push down the error handling into the scoring function instead of handling it at dispatch. Perhaps something like this might work:

```r
metric_score <- function(x, ...) {
  if (inherits(x, "error")) return(<apply error handler>)
  UseMethod(metric_score)
}

metric_score.pkg_metric_last_30_bugs_status <- function(x, ...) {
  mean(x, na.rm = TRUE)
}

attr(metric_score.pkg_metric_last_30_bugs_status, "label") <- 
  "A percentage of last 30 BugReports whose status is 'closed'"
```

The complication in here is that we'd need to use `getS3method("metric_score", class(assessment_output)` to pull the appropriate function to get the label, but we could assume that any assessment output would let us get the same information.
