### ISSUE TITLE
Fix CRAN/CI Build

### ISSUE THREAD

**Issue by elimillera** [pharmaR/riskmetric#147]
The CI is failing due to a few changes to dependencies  and documentation.

**Comment by elong0527** [comment]
enable github action

**Comment by dgkf** [comment]
As mentioned in #150, please use branch `feat/testing_kickoff` instead of `master` for this change. @elimillera and I will be overhauling our unit testing strategy in that branch and I want to avoid conflicts when we eventually pull this work into master as we'll all be touching different parts of the testing files.
