### ISSUE TITLE
Failed to execute iopages example

### ISSUE THREAD

**Issue by keaven** [pharmaR/riskmetric#166]
I did devtools::install_github("pharmaR/riskmetric") as instructed at iopages.
Then I ran example code as follows resulting in failure to find "assess()"
> library(riskmetric)
> 
> pkg_ref(c("riskmetric", "utils", "tools")) %>%
+     as_tibble() %>%
+     assess() %>%
+     score() %>%
+     mutate(risk = summarize_risk(.))
Error in assess(.) : could not find function "assess"

**Comment by dgkf** [comment]
Thanks @keaven - We need to update our GitHub pages. We just recently launched our GitHub actions which will handle deployments, so this shouldn't be an issue going forward. The issue you're facing is because we changed a few of the function names to avoid unwanted conflicts with other packages. You can try this instead:

```
pkg_ref(c("riskmetric", "utils", "tools")) %>%
  pkg_assess() %>%  # pkg_assess automatically handles tibble conversion
  pkg_score()       # pkg_score now handles the summarization as well
```

**Comment by dgkf** [comment]
@keaven We've now merged the updates to our continuous integration to link up with GitHub actions. Our documentation should now we automatically updated with each new pull request, so hopefully such issues with out-of-date documentation are a thing of the past. 

Please open another ticket if you find any other inconsistencies with the newly revamped docs.
