### ISSUE TITLE
Define a weights to aggregate risks from different metrics 

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#195]

**Comment by elong0527** [comment]
1. initiate a survey from community to be a potential source of defining weights. 

2. @marlycormar will initiate a pull request to discuss her proposal

**Comment by dgkf** [comment]
Just to add some more details - we discussed today some ideas as to how we might make the scoring function a bit more reproducible and data-driven. 

Even since the launch of `riskmetric`, one early idea was to try to derive a scoring algorithm based on a survey of savvy R users. We could
- poll savvy R users (ideally with relatively similar ideas of risk, such as selecting from a pool of pharma users) for their perceived risk of packages. 
- train a model to predict users' scores
- use this model to inform default weights, for exploring user impressions on software reliability and possibly embed this model with the package as the default scoring algorithm

Ideally we could provide anonymized data with the package as well as a vignette to reproduce the model to make the scoring function less arbitrary.

One idea was to use conference attendees and/or the R Validation Hub mailing list to solicit these initial user impression scores in order to kick this off.

**Comment by elong0527** [comment]
the shiny survey is on.
