### ISSUE TITLE
Mitigate `get_*`-style function repeated costly parsing / remote queries

### ISSUE THREAD

**Issue by dgkf** [pharmaR/riskmetric#20]
_inspired by conversation in #17, related to #18 conversation with @kkmann & @elong0527_

---

Thinking about downstream use of a `pkg_reference` object bit more critically, I also think we'll have to find a way to not repeatedly make costly queries for every `get_*`-style functions. For example, if we have `get_public_contributions`, `get_has_public_repo`, `get_bugreports_response_history` (just for sake of example), all of these might hit similar parts of the GitHub / GitLab apis. 

Instead of making repeated queries to an api or repeatedly reading in things like the `Meta/Rd.rds` file, how should we cache the results once for repeated use? Some options may include

1. Use `memoise` to cache these passively behind a in-package function call
2. Store reusable metadata within the `pkg_reference` and preferentially use metadata from within this structure any time a new query is being posed.
3. Use top-level `get_*` functions (e.g. `get_GitHub`) to query all relevant sub-queries and return a list of metadata objects for evaluation.

**Comment by kkmann** [comment]
Good one! Now, R is predominently pass-by-value but we have a few options:
1. memnonic functions (as used in packagemetrics package!)
2. R6 classes
3. passing environments (always passed by reference)

R6 is a bit overkill, memnonic functions are not that flexible, making references environments is probably the most R-ish way (if I am not mistaken the tensorflow package uses that too!)

**Comment by dgkf** [comment]
Interesting - I hadn't considered building an environment to namespace all of the results. I think that might be a good option. 

Perhaps then the `pkg_reference` structure should be an environment to collect intermediate results with a few attributes for specifying the source of where those should be gathered. 

My only concern with this approach is that we have to be very conscious about consistency of variables created within that environment such that we can call `get_public_contributions()` (which has a side effect of assigning `issue_participation_df` within the environment such that it can be reused once `get_bugreports_response_history()` is called. 

The solution would be to add getters and setters, but then we're practically rebuilding a class interface and might as well go with an R6 class. I'm usually not a fan of leaning on the more involved R object oriented systems, but I think it might be necessary to keep our sanity here.

**Comment by kkmann** [comment]
Think of an environment as the data part of an object, we then just tack on the class label 'pkg_reference' to handle method dispatch - that way we can get call by reference semantics in an R-ish style. added benefit: no dependency on R6 package ;)
My main concern with using a 'more sophisticated' class system is that it raises the entry barrier for potential contributors since R-folks don't commonly use these...
The only thing we would not have is 'private' data (for that you need R6) but the standard user would not mess with our environment anyway and it is much more straight forward to implement. I'd definitely go for the environment solution and simply store any potentially reusable stuff in it.
You'd then do things like checking whether the required variable exists in the `pkg_reference` object (=environment) and, if not, create it. I admit, from a CS point of view that sounds messy (and it is) but it surprisingly effective + hey, it's R ;)

If I get it right, the idea would thus be to use pkg_reference as base class that would get instantiated at the very beginning. All metrics would act on instances of pkg_reference with side effects (writing potentially reusable stuff to the underlying environment). Cool stuff!

**Comment by dgkf** [comment]
Okay, that's a good point about trying to avoid overcomplicating things. 

Where the R6 approach is definitely a bit more daunting to new contributors, the environment approach can be equally tricky to maintain because it's difficult to track down exactly what variables you should expect within the environment. If those ever get renamed in one place in the codebase, but not all, we'll end up duplicating those requests without any warning that something is wrong.

I think that it might be worth writing a bit of boilerplate to instantiate the environment with a limited set of bindings so that we can be more transparent about what a developer can expect to be available within it, then add some functions for modifying the environment that ensures new values aren't be introduced. At that point I feel like we must be reinventing some OO system wheel, but I'm not familiar enough with all the different OO systems to know if there's a better option.

**Comment by kkmann** [comment]
I'd say it's mainly a matter of taste, good ol' Hadley is certainly right in that R6 leads to a bit weird looking code (from an R user's perspective), https://adv-r.hadley.nz/r6.html. 
I wouldn't be too concerned about safety/managing of names - we should only use call by reference when it is really necessary since R is typically expected to work in a call by value fashion.
Let's go for S3 + environment for simplicity + idiomatic R code and, if we run into problems with that, we can still switch to R6 later (bit of a hassle, admittedly, but I am pretty sure we will not need it). The only ones tinkering with our pkg_reference objects will probably be our package methods and we should be able to manage that. 

@elong0527 ?

**Comment by elong0527** [comment]
For S3 + environment, I mainly be a user. I will support your decision by following the template defined and contribute further. 

Is it possible to provide me some background material to read? I want to understand how to avoid repeated calling the github api while using S3+environment like in the example @dgkf provide for

`get_public_contributions`, `get_has_public_repo`, `get_bugreports_response_history`

**Comment by dgkf** [comment]
@elong0527 

As an example, you could consider a `pkg_reference` object as just an `environment()` with a class attribute.

With this style, let's say you want the result of a GitHub query collecting issues from the last month. You might first check if a variable is declared in that environment before issuing the query. In its most simple form, it would look something like this:

```r
get_bugreports_response_history <- function(pkg, ...) {
  # at this point, pkg can be considered an `environment()` 
  # variable for all intents and purposes

  if (!exists("github_issues_history", envir = pkg)) {
    # issue your query and store in environment variable
    pkg$github_issues_history <- # make your query here
  }

  return(pkg$github_issues_history)
}
```

Nothing too fancy aside from hiding variables behind an environment. 

There are some guardrails I'd like to put on this to make sure that we don't find ourselves debugging silly things like accidentally checking if `"github_issue_history"` exists instead of `"github_issues_history"` - which wouldn't throw any sort of error and would work entirely as expected (albeit with extra calls to the github api), but at it's core this is how it would work.

**Comment by elong0527** [comment]
Thanks for the clarification. It is clear to me now and I also think we should use environment to avoid repeat parsing.
