### ISSUE TITLE
We need a hex logo

### ISSUE THREAD

**Issue by emilliman5** [pharmaR/riskmetric#233]

**Comment by emilliman5** [comment]
My meager attempts at a logo

![riskmetric_hex_logo](https://user-images.githubusercontent.com/7238842/154532857-cf1ebc4e-4623-49bd-b5be-97eafa9b8b80.png)

**Comment by kimjj93** [comment]
I like the second and third logos but isn't that pouncing horse image copyrighted?

**Comment by SHAESEN2** [comment]
I like the second/third as well but it does not represent what the package does very clearly. I think the first one is the better choice.

**Comment by AARON-CLARK** [comment]
@elimillera - just following up: did you ever reach out to a graphic designer at your company?

@emilliman5 et al.: just a heads up- the `{riskassessment}` dev team is working towards developing a hex logo - hopefully by the new year. We've had [a thread to brainstorm ideas](https://github.com/pharmaR/risk_assessment/issues/161) for a while. If interested, please take a look & provide feedback. If/when we get a few hex logos drafted, we'll be sure to share them with you.

Whatever the case, we want to make sure our hex is (1) aesthetically similar to `{riskmetric}` to build off each other's shared brand while also (2) conveying the differences between the two packages. There may be a better was to describe the relationship between the two packages, but to me: `{riskmetric}` provides nonbiased toolset to evaluate & quantify risk while `{riskassessment}` provides an infrastructure & forum to digest, assess, and categorize that risk within an organizational context.

Just an idea, but I'm wondering if you'd consider lady justice instead of the risk horseman? She is blindfolded & holding scales showcasing her unbiased evaluation.

![image](https://user-images.githubusercontent.com/17878953/203426841-dccc151e-4381-45a6-9000-34cfa99a47bc.png)

If `{riskmetric}` is lady justice, then that would make `{riskassessment}` the courtroom & jury, haha. Not sure how to draw that up yet. I (selfishly) do want to steal the hex logos (sorted by color) for the `{riskasessment}` hex since categorizing packages is probably the most important feature (or goal) of the application. May I re-purpose that idea in one of our drafts?

![image](https://user-images.githubusercontent.com/17878953/203427440-e87f70c7-54ea-4655-820c-bbeb566c3a51.png)

Any overall thoughts? Thanks!

**Comment by parmsam-pfizer** [comment]
Thought I'd throw an alternate hex into the mix. Here's one that I made using [flaticon](https://www.flaticon.com/free-icon/risk_4501338?term=risk%20level&page=1&position=6) and [Colin Fay's hexmake app](https://connect.thinkr.fr/hexmake/). We would need to provide attribution to the icon website if we use it: <a href="https://www.flaticon.com/free-icons/risk" title="risk icons">Risk icons created by Uniconlabs - Flaticon</a>

<img src="https://user-images.githubusercontent.com/107635309/203649186-3e7d50d6-a8eb-4f4b-a087-b3dcacff81e2.png" height=200px>

I also like the idea of coordinating the two hex stickers. Maybe the risk assessment hex could have some kind of [app or computer monitor image](https://www.flaticon.com/search?word=application&order_by=4) matched with the riskmetric logo we go with.

**Comment by AARON-CLARK** [comment]
Hi all,

I made a working draft based on everyone's clear interest in having some sort of scale/gauge. For `riskassessment`, I think having three distinct colors in the scale/gauge highlights the app's goal is to categorize packages into three groups: low, medium, and high risk. I was thinking the `riskmetric` version could have a more continuous gradient of colors to reflect the quantitative nature of the risk score. If people thinks that's a good idea, let me know and I'll try to work something up for `riskmetric`. I made a light and dark version below for fun:

![image](https://user-images.githubusercontent.com/17878953/205717752-0de3adfb-41c6-413a-aa3f-b7a3d72a00bc.png)

I think another idea to make the hex logos look different would be to share the same color for the work "risk" in the title, but have different colors for "metric" vs "assessment". 

I used [this icon](https://www.flaticon.com/free-icon/risk_2176912?term=risk&related_id=2176912#) as a base, but customized it quite a bit to include embedded hexes

**Comment by AARON-CLARK** [comment]
Hi @emilliman5 et al.,

Along my thought pattern shared above, here are a few `{riskmetric}` ideas, with a continuous color gradient, and some corresponding `{riskassessment}` ideas (below) as well. You'll notice I created a bunch of border/hex/title color variations to choose from.

![image](https://user-images.githubusercontent.com/17878953/206248572-a39907d7-9e56-4586-afe6-f9bd9785c9be.png)

And `{riskassessment}`, I changed the gauge's need to a cursor, and enclosed inside a browser window. Of course, the hex tiles on the gauge only show up in three colors, to reflect the user decision, assigning pkgs with the 'low', 'medium', or 'high' risk category.

![image](https://user-images.githubusercontent.com/17878953/206250266-6085bb3d-0c06-4bc0-b392-7d9c301e496a.png)

Thoughts?

**Comment by elimillera** [comment]
@AARON-CLARK It got a look but I haven't heard back. I love your hexes though! I would vote for the one in the top right

**Comment by emilliman5** [comment]
Team voted for #3 and #4 for riskmetric

**Comment by emilliman5** [comment]
Latest iterations

![d2a4968c-134e-4858-b6fc-1fc18ff8d2ba](https://user-images.githubusercontent.com/7238842/211841340-20d15f78-4eaa-4c4a-af54-61e223154929.jpg)
