### ISSUE TITLE
Unexpected missing components of pkg score

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaR/riskmetric#292]
Apologies in advance, this is likely user error!

I was trying to calculate the riskmetric for the {ggsurvfit} package, and the result includes `NA` values where I didn't expect them. For example, the `covr_coverage` value is missing, but the package has 100% covr coverage. Similarly, there are GH Actions setup to run R CMD Checks on various OSs and `remove_checks` is `NA`.

Should I be signaling this information differently somehow from my GH repo for them to be identified by the {riskmetric} pkg?

Thank you!!

``` r
library(riskmetric)
library(dplyr) |> suppressPackageStartupMessages()
packageVersion("riskmetric")
#> [1] '0.2.1'

pkg_ref("ggsurvfit") |>
  as_tibble() |>
  pkg_assess() |> 
  pkg_score() |> 
  select(package, version, pkg_score, covr_coverage, remote_checks, r_cmd_check,
         downloads_1yr, license) |> 
  purrr::imap_dfr(
    ~tibble(
      column = .y, 
      label = attr(.x, 'label'),
      value = as.character(.x)
    )
  )
#> # A tibble: 8 × 3
#>   column        value             label                                         
#>   <chr>         <chr>             <chr>                                         
#> 1 package       ggsurvfit         <NA>                                          
#> 2 version       0.3.0             <NA>                                          
#> 3 pkg_score     0.444927377824247 <NA>                                          
#> 4 covr_coverage <NA>              The fraction of lines of code which are cover…
#> 5 remote_checks <NA>              Weighted sum of OS flavor R CMD check results 
#> 6 r_cmd_check   <NA>              A weighted sum of errors/warnings/notes from …
#> 7 downloads_1yr <NA>              A logistic rating of the number of package do…
#> 8 license       <NA>              A binary indicator of whether the package shi…
```

<sup>Created on 2023-06-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by emilliman5** [comment]
Hi Daniel,

So the missingness in metrics is dependent on your pkg_ref source type. For instance, if your `pkg_ref` is of type `cran_remote`, you won't get code coverage becasue this ref source does not (currently) have access to the source code to run unit tests. However, if your `pkg_ref` source is `pkg_source` then you would get a code coverage metric. Likewise, for `remote_checks` the situation would be reversed. 

In general, we try to keep metrics tightly coupled to `pkg_ref` sources. In the above example, when your `pkg_ref` is a `pkg_source` we cannot be sure that CRAN's remote check results apply to the source code you are referencing.  For a package that focuses on risk/quality we'd rather omit a metic if we can't be sure it is directly attributable to the `pkg_ref`. 

First thing to check is what your source is in the above example, `pkg_ref("ggsurvfit")$source`. For example, when I run your above example I do get a metric for `remote_checks` because `pkg_ref` returns a `pkg_cran_remote` source type, while I suspect you are creating a `pkg_install`

Second, we have been discussing the implementation of chaining source types, so that a broader set of metrics can be scored for a package, which would allow us to provide more complete metrics, without the user having to worry about maintaining a provenance chain for the various ref sources.
