### ISSUE TITLE
Mitigating namespace conflicts

### ISSUE THREAD

**Issue by dgkf** [pharmaR/riskmetric#77]
As @mpadge raised in #69, we run a bit of a risk of over generalizing our function names. I think this is a valid concern given the over-generality of our naming conventions.

Given that these functions are more specific than their current names really warrant, I'd personally prefer to make the function names reflect the specificity instead of solving the problem by adding a package prefix. Perhaps we could consider something like:
- `assess_package` or `assess_metric`
- `score_package` or `score_metric`

@mpadge also highlighted our vestigial `coverage` function that I think is an artifact of some early work that was done to try to explore some coverage assessments well before the rest of the structure of the package was in place. Given how much things have changed since then, I think we can scrap that code and work it back in once we want to tackle some of the more computationally intensive metrics like cohort, package and function test coverage.

**Comment by elong0527** [comment]
I like the idea. After we have an agreement for the prefix of the function names, I can re-org the pkgdown reference page to make it in a logical way. 

https://pharmar.github.io/riskmetric/reference/index.html

In general, I agree and think we shall group our functions using the four verbs in our workflow.

**Comment by dgkf** [comment]
Just revisiting this, as I'd like to make the change soon. Just to throw out some possible naming conventions. How would people feel about `pkg_assess` and `pkg_score`? 

Of the prefixed style of naming conventions, I like this one because (1) the prefix contributes to the meaning of the function and (2) it resembles our existing `pkg_*` class and constructor naming convention.

Just to put a timeline on the change, let's aim to have a consensus by end of March so we can make the change before we start inviting more eyes to the project.

**Comment by elong0527** [comment]
good for me. Is it true all four verbs will be with a prefix `pkg_`?

**Comment by dgkf** [comment]
Are these the four that you're thinking of?

1. `pkg_ref`
2. `pkg_assess`
3. `pkg_score`
4. `pkg_summarize_risk`

The only one that feels weird to me is `pkg_summarize_risk`... it seems longer than necessary. Maybe we can think of something more succinct and direct? Perhaps just `pkg_risk`?

**Comment by elong0527** [comment]
Yes, `pkg_risk` is good. Just want to match the concept in the Vignettes 

https://github.com/pharmaR/riskmetric/blob/master/vignettes/riskmetric.Rmd

**Comment by dgkf** [comment]
Definitely - we'll have to do a thorough sweep to change it regardless of what we choose. If we're happy with that naming scheme, let's let the issue sit for a bit to give an opportunity for anyone else to weigh in. 

Especially for `pkg_risk`, I'd be interested to hear other thoughts as to whether this would remain clear enough. Any other feedback about the prefix or suggestions for alternatives would be appreciated as well.

**Comment by mpadge** [comment]
If I may, one suggestion from my side: I appreciate that the context for all of you is "*risk*", but what you're building is actually more general than that. I've been talking up your work a lot, and do definitely intend to build directly upon it, yet not in a risk context at all. You'd stand a better chance of widespread adoption if it was perhaps named more generally. That just returned to the above potential ambiguity between `pkg_score` and `pkg_summarize_risk`, or whatever. How about the final fn be `pkg_report`, because risk is one mode of reporting the summary statistics? This is just intended as a suggestion, and i'd totally understand if you'd prefer for the sake of focus to keep to your own intentions.

**Comment by dgkf** [comment]
Thanks @mpadge - it's easy to hone in on our use-case. I appreciate the broader perspective. Brainstorming (with help from thesaurus.com), here are some alternatives that stand independent of the regulated industry context:

`pkg_rating`
`pkg_rate`
`pkg_grade`
`pkg_score` (with current `pkg_score` function renamed if that makes more sense?)

Thinking about it a bit more, `pkg_score` doesn't quite seem to fit as a renaming of `score`. `score` (referring to the assessment-output-targetted `score.pkg_metric_*`  functions) makes sense, but then it might more appropriately be something like `metric_score` instead of `pkg_score`. `score.tbl_df` is just a convenient shorthand for applying this function to each of the outputs of the assessments when wrapped in a `tibble`. 

This function is more of a normalization to a single numeric scale (per assessment output) and I wouldn't be opposed to renaming it to something more indicative of that while we're doing a renaming sweep.

**Comment by elong0527** [comment]
During the meeting, we discussed the possibility to use `pkg_score` to cover both metric score and overall package score. The two parts can be an individual sub_routine.  In this way, we may use three verbs to handle the workflow.

1. pkg_ref
1. pkg_assess
1. pkg_score

**Comment by dgkf** [comment]
I'm going to run with this style, which spans a small spectrum of very type-stable functions to more user-friendly ways of operating on data with minimal programming overhead:

- On a single `pkg_ref`, use specific `assess_*` functions to assess exact metric. Then use `metric_score` to dispatch scoring behavior on specific `pkg_metric_*` return types.
- On a single `pkg_ref` use `pkg_assess` to return a named `<list_of<pkg_metric>>` of `assess_*` results. `pkg_score` applied to a `<list_of<pkg_metric>>` returns a named numeric vector. Can use `summarize_risk` (possibly rename to step away from "risk" language?) to get a single package score.
- On a `pkg_ref` `tibble`, `pkg_assess` and `pkg_score` can be used to apply a list of assessments and subsequently score them individually while _also_ providing an overall score.

I think that this reduces a good amount of complexity in the user facing functions while still providing good flexibility if someone needs to dig into the details.

**Comment by elimillera** [comment]
The above is all very well thought out. I think the [xml2](https://github.com/r-lib/xml2/blob/master/NAMESPACE) package has excellent flow for programming because of their well thought out function names. As @mpadge said, our problem is a little more challenging because our goal is broader than working with XML data. I've been thinking about how I would use this process when reviewing a package or writing about its use in a validation report, and IMO the convention `pkg_*` makes a lot of sense to me, as does the `pkg_score` function doing double duty.

I think we need to be careful about how we phrase the final step of the process(currently `summarize_risk`) is phrased. I've used this to review a couple of packages, and I'm thinking about how I would use the output to improve a validation report. I would be hesitant to call the packages or functions I used 'risky' even if a knowledgeable reviewer could understand the context.

On that topic, I think one big thing that we could work to provide is the context of these results. I can find out how many times a package has been downloaded, if it has a maintainer, etc, but I'm not sure how to weigh these things across packages. I'm thinking this could be a good idea for a vignette!

**Comment by dgkf** [comment]
Thanks @elimillera - I completely agree about renaming `summarize_risk`. As well, I think we might want its current implementation to shoot off a message or warning. Currently it's a bit of a placeholder function embedding some loose intuition. As is, it's mostly for demo purposes.

Long term I'd love to survey a bunch of savvy R programmers and use a regression to come up with something a bit more data-driven, even if it is just our best guess at a community consensus.

Back to the API renaming - I'll move forward with the PR to introduce the new prefixed convention.

**Comment by elong0527** [comment]
* suggest to rename `summarize_risk` to `summarize_score`
