### ISSUE TITLE
Updated Vignette review and feedback 

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#84]
Once #74 and #75 completed. Review the Vignette and provide feedbacks.

**Comment by bzkrouse** [comment]
_Comments on first vignette:_
@dgkf  - just reviewed the correct version of the 1st vignette - great job!! Really like the addition of the diagram and extra clarifications on classes/caching. I think this very clear and great as-is but here are a couple of small comments to consider in later iterations:

- Step 2. caching is happening behind the scenes, but giving it a bullet point in the Intro section might give the user the impression they need to perform that step (since they see that prior to the workflow example).  An alternative could be folding the caching concept into Step 3. Assess, in the context of where the assess functions look for metadata.
- A diagram could be useful for explaining the caching workflow, or for what things look like when you are pulling from multiple sources

**Comment by dgkf** [comment]
Thanks @bzkrouse - I've pulled in a bunch of the feedback in #98. Going to close the issue, but please feel free to continue to provide feedback if you see anything that looks like it wasn't addressed.
