### ISSUE TITLE
Identify the way to collect release date on CRAN

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#85]

**Comment by mpadge** [comment]
It's also simultaneously useful and important to collect info on *first* release date, as well as release *rates* (#65), and for those you need a full local clone of CRAN + the `/archive` directory. We currently just CRON that on a daily basis and use that to extract all those stats. Since the local clone is needed to do most of the core package analyses anyway, this just requires one additional line in the CRON job to grab the `/archive` directory.

**Comment by dgkf** [comment]
@mpadge - Agree about the importance of both first release date (and time since first release), as well as release rate. Just to make sure I'm understanding you correctly, you're suggesting a daily mirror of [https://cran.r-project.org/src/contrib/Archive/]() when you mention the `/archive` directory as a means of collecting this info?

How would you like to see this work within `riskmetric`? For a `cran_remote` this seems quite manageable, but for an `install` or `source` reference it might require somehow associating local files with a CRAN remote such that we can confidently use the archival data. 

This might speak to a bigger need to first verify that the locally installed or local source code is reflective of a version on CRAN. At some point we need to tackle a more rigorous way of comparing package versions - likely via a hash to differentiate instances of code that may be tagged with the same package version.

**Comment by mpadge** [comment]
@dgkf yes, the `src/contrb/Archive` directory is what i mean, and yes, you are right that for an `install` or `source` reference this is then not straightforward. It's also of course different for bioconductor, which does not have a package-based archive at all. You/us/we would have to (read: "are likely going to have to") construct a way to turn the bioconductor version-based archive into an equivalent package-based archive. Having that ability for both CRAN and bioconductor should cover *most* use cases, then just leaving the edge cases for which we'd need to ask maintainers to provide some kind of systematic information for extraction of archival versions.
